### PR TITLE
Perserve user command history

### PR DESCRIPTION
**Pull request by timneutkens**
Haven't managed to fix the bug you talked about yet.

### CODE REVIEW

**Comment by timneutkens** [comment]
@geowarin can you check it one last time ❤️. Dropped the dependency on get cursor position and went with another solution instead. It will persist the history and leave functionality like it is at the moment. Only difference is that every time we clear the cleared message will be moved to the history instead of being deleted. I actually like this because if you want to have a look at what happened in previous reloads you can. It doesn't bloat the output also, so when working you always have the clean last message.

**Comment by geowarin** [comment]
To be honest, I don't really see a difference with the previous version. :persevere:

Also, here is [the console sequence](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/clearConsole.js) used by create-react-app.

I don't really understand all this ANSI magic. Do you ?

**Comment by timneutkens** [comment]
I've been looking for the right ansi sequence all over, tried around 10 of them. The one Dan added *is* the correct one :joy:

**Comment by geowarin** [comment]
Indeed, and thank you very much for taking the time :1st_place_medal:

**Comment by geowarin** [comment]
Just to be sure, does it solve [next's issue](https://github.com/zeit/next.js/issues/1070) ?
It seems to wipe my history like before.

**Comment by timneutkens** [comment]
Awh, seems like this wipes the visible history 😢

**Comment by timneutkens** [comment]
Which my previous solution doesn't

**Comment by timneutkens** [comment]
Would love to invite you to https://zeit.chat btw 👍

**Pull request merged**
