### PR TITLE
feat: group module not found errors

### PR DESCRIPTION
**Pull request by christophehurpeau**
closes:  #30 (except for yarn)

### CODE REVIEW

**Comment by geowarin** [comment]
This looks awesome, thank you!

**Comment by geowarin** [comment]
Released in v1.5.0

**Comment by christophehurpeau** [comment]
@geowarin you're too fast ! There a fix I wanted to add :)

**Comment by christophehurpeau** [comment]
Also related:  #5

**Comment by geowarin** [comment]
Whoops! It works fine though doesn't it ?
I can give you write access to the repo if you're interested

**Comment by christophehurpeau** [comment]
@geowarin yes it works but relative paths starting with `../` are considered as dependencies
I'd be honored !

**Pull request merged**
