### PR TITLE
Preserve user command history

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes https://github.com/zeit/next.js/issues/1070

Basically what it does is start the output of friendly-errors-webpack-plugin at the line the command is ran. Any re-renders will remove the lines below that point. I've also accounted for the fact that someone might clear his output. When you do that it will start at the beginning as it's supposed to.

### CODE REVIEW

**Comment by timneutkens** [comment]
screen shot 2017-02-12 at 23 41 31

**Comment by timneutkens** [comment]
Ready for merge.

**Comment by geowarin** [comment]
Hello @timneutkens.
Thank you for this PR, it looks amazing.

Any idea why the travis build is failing ?

**Comment by timneutkens** [comment]
I have No idea. Lets trigger a rebuild.

**Comment by timneutkens** [comment]
./build/Release/pos is included in get-cursor-position. Investigating.

**Comment by geowarin** [comment]
FYI, I updated the master with unrelated changes but you will have to rebase.
I'm also looking at your branch to try to understand CI failure.
Would it help if I cleared travis cache ?

**Comment by timneutkens** [comment]
@geowarin I'm thinking it might be a bug in get-cursor-position which i didn't encounter since I'm on a mac (case-insensitive filesystem)

**Comment by geowarin** [comment]
It looks like it uses a native module that might not get compiled on Linux?
I wish I could ssh into the machine to check it out.
I'm on a mac also and I can't reproduce

**Comment by geowarin** [comment]
Oh yeah, you're right: https://github.com/bubkoo/get-cursor-position/issues/2

**Comment by timneutkens** [comment]
The weird thing is, on mac the `Release` directory has the uppercase `R`

`./node_modules/get-cursor-position/build/Release/pos.node`

**Comment by geowarin** [comment]
Well, no luck. It seems worse than the casing problem.

I'm not a node-gyp expert so that's all I can do, I'm afraid.

**Comment by geowarin** [comment]
Well, I got it to work somehow. Thanks @patrickkettner ;)
I would be a little bit more at ease if a couple of people could test this on their Linux/Windows machine, though.

What do you think @timneutkens ?

**Comment by timneutkens** [comment]
Right, I'll ping some people ❤️

**Comment by timneutkens** [comment]
@patrickkettner 
On windows with node 7.4.0 we get this:
pasted_image_at_2017_02_14_01_18_pm

**Comment by geowarin** [comment]
I believe that's related to the compilation of the native module.
They are compiled when you install them and some of them require the same version of node to be run with.
Long story short, `rm -rf node_modules` should get rid of the error.

We could set up an appveyor build to try and reproduce the windows build, if necessary.

**Comment by timneutkens** [comment]
They are actually pre-compiled in the repository

**Comment by patrickkettner** [comment]
that is a failure on my module. I node-pre-gyp the versions to try to avoid native compilation (in fact my namedspaced module is just a node-pre-gypped version of https://www.npmjs.com/package/get-cursor-position

I apparently precompiled the wrong version for 7.4

**Comment by timneutkens** [comment]
@patrickkettner if you could recompile it that would be amazing ❤️ 😍

**Comment by patrickkettner** [comment]
course. will ping when published

**Comment by timneutkens** [comment]
Thank you very much 👍

**Comment by patrickkettner** [comment]
should be good

**Comment by geowarin** [comment]
I went ahead and merge this, it seems to work fine on CI (both windows and linux).
Thank you very much to both of you!

The only concern is the [node 5](https://travis-ci.org/geowarin/friendly-errors-webpack-plugin/jobs/201861912) build which seems to hang forever.
Any idea ?
I'm pretty sure it's related to get-cursor-position.

**Comment by geowarin** [comment]
@timneutkens I screwed up when merging your branch, I actually didn't mean to do it like this.

If you're ok with this, I'm going to force push to master to revert the merge commit (don't judge me).

Would you mind opening another PR afterwards ?
FYI, I noticed a problem when the output is too big to fit in the remaining screen space (for instance you hit enter a bunch of time before launching webpack).

I'm going to commit a sandbox project making it easy to reproduce the problem.
Can you confirm you wouldn't mind opening another PR ? Really sorry about this.

**Comment by timneutkens** [comment]
Sure, no worries!

**Comment by geowarin** [comment]
I rolled back your change.
Again, I'm really sorry about this, I messed up.

If you don't mind opening another PR with your change, you can use the _sandbox project to test your PR.
For instance, try to remove the `/* eslint-disable */` comment in `_sandbox/index.js` with only a tiny bit of screen space remaining. In this case, the console will not be cleared properly.

CI should now build on both linux and windows and that will help discussing your change.

**Pull request merged**
