### PR TITLE
fix: relative module with ../

### PR DESCRIPTION
**Pull request by christophehurpeau**

### CODE REVIEW

**Comment by christophehurpeau** [comment]
closes #5

**Comment by christophehurpeau** [comment]
@geowarin perhaps we can change the presentation of the moduleNotFound if it's a dependency or relative module:
```js
expect(logs).toEqual([
    'ERROR  Failed to compile with 2 errors',
    '',
    'These relative modules were not found:',
    '',
    '* ./non-existing in ./test/fixtures/module-errors/index.js',
    '* ../non-existing in ./test/fixtures/module-errors/index.js',
    '',
    'This dependency was not found:',
    '',
    '* not-found in ./test/fixtures/module-errors/index.js',
    '',
    'To install it, you can run: npm install --save not-found'
  ]);
```

?

**Comment by geowarin** [comment]
Yes, I like it

**Comment by christophehurpeau** [comment]
@geowarin updated with new formatter

**Comment by geowarin** [comment]
Excellent! Thank you so much :1st_place_medal: 
Do we release a 1.6.0 ?

**Comment by christophehurpeau** [comment]
🎉 yes !

**Comment by geowarin** [comment]
Released in 1.6.0

**Comment by christophehurpeau** [comment]
@geowarin that is weird, the travis check for the second commit `e1a6b26` points to [build 131](https://travis-ci.org/geowarin/friendly-errors-webpack-plugin/builds/206196586) which is for an older commit `b6bdc94` (rebased later as `621a8a6`) Perhaps a racing condition and a bug in travis ?

**Comment by geowarin** [comment]
It might also be that we use babel with jest and it might subtly transform the tested code behind the scenes.
Maybe we need a smoke test without jest.

**Pull request merged**
